[ZABBIX]

url = https://
token = 

[NETBOX]

url = https://
token = 

[PROXMOX]

#id proxmox template in zabbix
template_id = 10517
role_vm = 76
domain =

[KVM]

#id kvm_vm template in zabbix
template_id = 11301
role_vm     = 76
cluster     = KVM